# .github/workflows/deploy.yml
name: Build and Deploy

on:
  push:
    branches:
      - main # Trigger the workflow when code is pushed to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Make sure to add your Firebase token to GitHub secrets
        run: firebase deploy
